name: dtwa
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.14.3
  - pip
  - numpy=2.4.4
  - scipy=1.17.1
  - matplotlib=3.10.8
  - qutip=5.2.3
  - tqdm=4.67.3
  - pillow=12.1.1
  - ipykernel=7.2.0
  - pip:
      - jax==0.9.2
      - jaxlib==0.9.2
      - jax-cuda13-pjrt==0.9.2
      - jax-cuda13-plugin==0.9.2
      - nvidia-cudnn-cu13==9.20.0.48
      - diffrax==0.7.2
      - equinox==0.13.6
      - lineax==0.1.0
      - jaxtyping==0.3.9
      - optax==0.2.6
      - optimistix==0.1.0
      - ml-dtypes==0.5.4
      - wadler-lindig==0.1.7